# appveyor.yml from https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:

    # Python 2.7.10 is the latest version and is not pre-installed.

    # PYTHON: "C:\\Python27.10"
    # PYTHON_VERSION: "2.7.10"
    # PYTHON_ARCH: "32"

    # PYTHON: "C:\\Python27.10-x64"
    # PYTHON_VERSION: "2.7.10"
    # PYTHON_ARCH: "64"

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "64"

    # PYTHON: "C:\\Python33"
    # PYTHON_VERSION: "3.3.x" # currently 3.3.5
    # PYTHON_ARCH: "32"

    # PYTHON: "C:\\Python33-x64"
    # PYTHON_VERSION: "3.3.x" # currently 3.3.5
    # PYTHON_ARCH: "64"

    # PYTHON: "C:\\Python34"
    # PYTHON_VERSION: "3.4.x" # currently 3.4.3
    # PYTHON_ARCH: "32"

    # PYTHON: "C:\\Python34-x64"
    # PYTHON_VERSION: "3.4.x" # currently 3.4.3
    # PYTHON_ARCH: "64"

    # Python versions not pre-installed

    # Python 2.6.6 is the latest Python 2.6 with a Windows installer
    # See: https://github.com/ogrisel/python-appveyor-demo/issues/10

    # PYTHON: "C:\\Python266"
    # PYTHON_VERSION: "2.6.6"
    # PYTHON_ARCH: "32"

    # PYTHON: "C:\\Python266-x64"
    # PYTHON_VERSION: "2.6.6"
    # PYTHON_ARCH: "64"

    # PYTHON: "C:\\Python35"
    # PYTHON_VERSION: "3.5.0"
    # PYTHON_ARCH: "32"

    # PYTHON: "C:\\Python35-x64"
    # PYTHON_VERSION: "3.5.0"
    # PYTHON_ARCH: "64"

    # Major and minor releases (i.e x.0.0 and x.y.0) prior to 3.3.0 use
    # a different naming scheme.

    # PYTHON: "C:\\Python270"
    # PYTHON_VERSION: "2.7.0"
    # PYTHON_ARCH: "32"

    # PYTHON: "C:\\Python270-x64"
    # PYTHON_VERSION: "2.7.0"
    # PYTHON_ARCH: "64"

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"

  # Install the build dependencies of the project. If some dependencies contain
  # compiled extensions and are not provided as pre-built wheel packages,
  # pip will build them from source using the MSVC compiler matching the
  # target Python version and architecture
  - "%CMD_IN_ENV% pip install -r requirements.txt"

  # Requirement for binary build
  - "%CMD_IN_ENV% pip install http://sourceforge.net/projects/py2exe/files/latest/download?source=files"

  # fix missing init.py for zope
  - ps: "New-Item -ItemType file $env:PYTHON/Lib/site-packages/zope/__init__.py"

build_script:
  # Build the compiled extension
  - "%CMD_IN_ENV% python setup.py install"

#test_script:
  # Run the project tests
  #- "pip install nose"
  #- "%CMD_IN_ENV% python setup.py nosetests"

after_test:
  # If tests are successful, create binary packages for the project.
  - "%CMD_IN_ENV% python setup.py py2exe"
  - ps: "Move-Item dist disttemp"
  - ps: "New-Item -ItemType directory -Path dist/dataserv-client"
  - ps: "Move-Item disttemp/* dist/dataserv-client"
  - ps: "cd dist"
  - 7z a dataserv-client.win%PYTHON_ARCH%.zip dataserv-client\*  

artifacts:
- path: dist\dataserv-client.win32.zip
  name: dataserv-client.win32.zip
- path: dist\dataserv-client.win64.zip
  name: dataserv-client.win64.zip
  
deploy:
- provider: GitHub
  tag:
  release: autobin draft release
  auth_token:
    secure: bPlHCdaxjgVJXAW2CooVSnyJr0pHg+qu2HdsS27HgVDRRXlTO+mgMk7V3+N/OTe+
  artifact: /.*\.zip/
  draft: true
  on:
    branch: master

